### ISSUE TITLE
Week 3 Plan

### ISSUE THREAD

**Issue by yuliiapiguliakCU** [CU-CSCI3308-Spring2024/Recitation-014-Team-02#28]
- [x] #1 by Daniel Folino
- [x] #9 by Daniel Folino
- [x] #11 by Daniel Folino
- [x] #18 by Kate Ehrnstrom
- [x] #12 by Kate Ehrnstrom
- [x] #21 by Chloé Wolff de Grivel Perrigny
- [x] #23 by Carter Sammis
- [x] #33 by Daniel Folino
- [x] #44 by Daniel Folino
- [x] #45 by Chloé Wolff de Grivel Perrigny
- [x] #46 by Chloé Wolff de Grivel Perrigny and Daniel Folino
- [x] Add more UI to the experience when all tasks are complete
