### ISSUE TITLE
Week 4 Plan

### ISSUE THREAD

**Issue by yuliiapiguliakCU** [CU-CSCI3308-Spring2024/Recitation-014-Team-02#53]
- [x] #25 by Yuliia Piguliak
- [x] #24 by Carter Sammis
- [x] #10 by Carter Sammis
- [x] #29 by Daniel Folino
- [x] #60 by Kate Ehrnstrom
- [x] #71  by Daniel Folino
- [x] Add more UI to the experience when all tasks are complete
