### ISSUE TITLE
Week 5 Plan

### ISSUE THREAD

**Issue by yuliiapiguliakCU** [CU-CSCI3308-Spring2024/Recitation-014-Team-02#70]
- [x] #3  by Yuliia Piguliak
- [x] #74 by Chloé Wolff de Grivel Perrigny
- [x] #21 by Chloé Wolff de Grivel Perrigny
- [x] #19 by Kate Ehrnstrom
- [x] Add more UI to the experience when all tasks are complete
- [ ] Improve Currency Search Results UI by Ethan Schrauf
